### ISSUE TITLE
SPIKE: connecting our snap to go-nitro RPC server

### ISSUE THREAD

**Issue by geoknee** [statechannels/nitro-gui-archive#8]
How do we get data to and from go-nitro from our snap?

**Comment by geoknee** [comment]
Related to https://github.com/statechannels/go-nitro/issues/1180

**Comment by geoknee** [comment]
An early goal is to talk to go-nitro from a javascript environment (could be node or browser). This branch will be useful https://github.com/statechannels/go-nitro/pull/1200

**Comment by lalexgap** [comment]
We now have a an RPC server in go-nitro and a typescript rpc client, so it should be pretty easy to talk to a go-nitro rpc server. 

@geoknee Should we try hooking this using storybook? Or should we start writing an actually website/snap UI?

**Comment by geoknee** [comment]
@lalexgap I think since this issue was created we have steered somewhat away from metamask snaps for the time being. I think we do still want to wire up our GUI to a go-nitro RPC server though, for sure. 

I think storybook may not be the best choice, since I think that is more for unit testing components. Let's discuss at standup today.
